swagger: '2.0'
info:
  version: "v1.0"
  title: WSO2 API Manager OAuth2 Dynamic Client Registration Endpoint
  description: >
    This document specifies an **OAuth2 Dyanmic Client Registration Endpoint**
    for WSO2 **Identity Server** .
    It is written with [swagger 2](http://swagger.io/).
  contact:
    name: WSO2
    url: 'http://wso2.com/api-management'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - https
host: localhost
basePath: /api/identity/oauth2/dcr/v1.0
securityDefinitions:
  basicAuth:
    type: basic
  OAuth2Security:
    type: oauth2
    flow: password
    tokenUrl: https://localhost:9443/token

consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    post:
      description: |
        This API is used to create an OAuth2 application.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":["https://client.example.org/callback"],
          "client_name": "application_1",
          "ext_param_owner": "application_owner",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.0/register"
      x-wso2-response: |
        "HTTP/1.1 201 Created"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "client_name":"application_owner_application_1" }
      summary: |
        Registers an OAuth2 application
      operationId: registerApplication
      parameters:
        - name: registrationRequest
          in: body
          description: Application information to register.
          required: true
          schema:
            $ref: '#/definitions/RegistrationRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Application'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - OAuth2 DCR
# Endpoint to get application information
  /register/{client_id}:
    get:
      summary: |
        Get OAuth2 application information
      description: |
         This API is used to get/retrieve an OAuth2 application by client_id.
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.0/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "client_name":"application_owner_application_1" }
      operationId: getApplication
      parameters:
        - name: client_id
          type: string
          in: path
          description: Unique identifier of the OAuth2 client application.
          required: true
      responses:
        '200':
          description: Successfully Retrieved
          schema:
            $ref: '#/definitions/Application'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - OAuth2 DCR
# Endpoint to delete OAuth2 application
    delete:
      summary: |
        Delete OAuth2 application
      description: |
         This API is used to delete an OAuth2 application by client_id.
      x-wso2-request: |
        curl -X DELETE -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.0/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 204 No Content"
      operationId: deleteApplication
      parameters:
        - name: client_id
          type: string
          in: path
          description: Unique identifier of the OAuth2 client application.
          required: true
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - OAuth2 DCR
# Endpoint uses to update OAuth2 application
    put:
      description: |
        This API is used to update an OAuth2 application.
      x-wso2-request: |
        curl -X PUT -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":["https://client.example.org/callback"],
          "client_name": "application_1",
          "ext_param_owner": "application_owner",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.0/register"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "client_name":"application_owner_application_1" }
      summary: |
        Updates an OAuth2 application
      operationId: updateApplication
      parameters:
        - name: updateRequest
          in: body
          description: Application information to update.
          required: true
          schema:
            $ref: '#/definitions/UpdateRequest'
        - name: client_id
          type: string
          in: path
          description: Unique identifier for the OAuth2 client application.
          required: true
      responses:
        '200':
          description: Successfully updated
          schema:
            $ref: '#/definitions/Application'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - OAuth2 DCR

definitions:
#-----------------------------------------------------
# The Registration Request Object
#-----------------------------------------------------
  RegistrationRequest:
    type: object
    required:
      - redirect_uris
      - client_name
    properties:
      redirect_uris:
        type: array
        items:
          type: string
      client_name:
        type: string
      grant_types:
        type: array
        items:
          type: string
      token_expire_time:
        type: integer
        format: int64

#-----------------------------------------------------
# The Application Update Request Object
#-----------------------------------------------------
  UpdateRequest:
    type: object
    properties:
      redirect_uris:
        type: array
        items:
          type: string
      client_name:
        type: string
      grant_types:
        type: array
        items:
          type: string
      token_expire_time:
        type: integer
        format: int64
#-----------------------------------------------------
# The OAuth2 Application Object
#-----------------------------------------------------
  Application:
    type: object
    properties:
      client_id:
        type: string
      client_secret:
        type: string
      client_secret_expires_at:
        type: string
      redirect_uris:
        type: array
        items:
          type: string
      client_name:
        type: string
      grant_types:
        type: array
        items:
          type: string
      token_expire_time:
        type: integer
        format: int64
#-----------------------------------------------------
# The Error Response object
#-----------------------------------------------------
  Error:
    type: object
    properties:
      code:
        type: string
      httpStatusCode:
        type: integer
      message:
        type: string
      description:
        type: string
      moreInfo:
        type: string