CREATE TABLE IF NOT EXISTS AUTH_OAUTH2_CLIENTS (
            CLIENT_ID VARCHAR(256),
            CLIENT_SECRET VARCHAR(512),
            REDIRECT_URI VARCHAR(1024) DEFAULT NULL,
            PRIMARY KEY (CLIENT_ID)
);

CREATE TABLE IF NOT EXISTS AUTH_OAUTH2_AUTHORIZATION_CODE (
            CODE_ID INTEGER NOT NULL AUTO_INCREMENT,
            CLIENT_ID VARCHAR(256),
            AUTHORIZATION_CODE VARCHAR(512),
            REDIRECT_URI VARCHAR(1024) DEFAULT NULL,
            SCOPE VARCHAR(2048),
            PRIMARY KEY (CODE_ID)
);

CREATE TABLE IF NOT EXISTS AUTH_OAUTH2_APPLICATION (
            ID INTEGER NOT NULL AUTO_INCREMENT,
            CLIENT_ID VARCHAR(255),
            CLIENT_SECRET VARCHAR(512),
            APP_NAME VARCHAR(255),
            OAUTH_VERSION VARCHAR(128),
            REDIRECT_URI VARCHAR(1024) DEFAULT NULL,
            GRANT_TYPES VARCHAR (1024) DEFAULT NULL,
            APP_STATE VARCHAR (25) DEFAULT 'ACTIVE',
            USER_ACCESS_TOKEN_EXPIRE_TIME BIGINT DEFAULT 3600000,
            APP_ACCESS_TOKEN_EXPIRE_TIME BIGINT DEFAULT 3600000,
            REFRESH_TOKEN_EXPIRE_TIME BIGINT DEFAULT 84600000,
            CONSTRAINT CLIENT_CONSTRAINT UNIQUE (CLIENT_ID, CLIENT_SECRET),
            PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AUTH_OAUTH2_ACCESS_TOKEN (
            TOKEN_ID INTEGER NOT NULL AUTO_INCREMENT,
            ACCESS_TOKEN VARCHAR(512),
            REFRESH_TOKEN VARCHAR(512) DEFAULT NULL,
            APPLICATION_ID INTEGER,
            GRANT_TYPE VARCHAR (50),
            ACCESS_TOKEN_TIME_CREATED TIMESTAMP(6) DEFAULT 0,
            REFRESH_TOKEN_TIME_CREATED TIMESTAMP(6) DEFAULT 0,
            ACCESS_TOKEN_VALIDITY_PERIOD BIGINT,
            REFRESH_TOKEN_VALIDITY_PERIOD BIGINT,
            TOKEN_STATE VARCHAR(25) DEFAULT 'ACTIVE',
            FOREIGN KEY (APPLICATION_ID) REFERENCES AUTH_OAUTH2_APPLICATION(ID),
            PRIMARY KEY (TOKEN_ID)
);
